language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  allow_failures:
    - php: hhvm

before_script:
    - composer install

script:
    - php tests/test.php